apiVersion: v1
kind: ConfigMap
metadata:
  name: fiu-service-app-config
data:
  application.properties: |  # Combine your configurations into one file
    spring.datasource.url=jdbc:postgresql://10.234.48.3:5432/fiu_datastore?useSSL=false
    spring.datasource.username=postgres
    spring.datasource.password=OMITTED
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    app.fiu.fiu-id=setu-fiu-id
