apiVersion: v1
kind: ConfigMap
metadata:
  name: fiu-application-config
data:
  application.properties: |  # Combine your configurations into one file
    spring.datasource.url=jdbc:postgresql://10.7.0.3:5432/fiu_datastore?useSSL=false
    spring.datasource.username=fiu-application
    spring.datasource.password=OMITTED
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    app.fiu.fiu-id=setu-fiu-id
    management.endpoints.web.exposure.include=health, prometheus
    management.endpoint.prometheus.enabled=true
