apiVersion: v1
kind: ConfigMap
metadata:
  name: fiu-application-config
  labels:
    app: fiu-application
data:
  application.properties: |  # Combine your configurations into one file
    spring.datasource.url=jdbc:postgresql://172.22.0.3:5432/fiu_datastore?useSSL=false
    spring.datasource.username=fiu-application
    spring.datasource.password=${sm://database-password}
    spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    app.fiu.fiu-id=setu-fiu-id
    app.fiu.setu-uri=https://fiu-uat.setu.co
    app.fiu.setu-client-id=f26b25b8-8e33-4c86-a28e-4575ddeeb09a
    app.fiu.setu-client-secret=${sm://setu-client-secret}
    management.endpoints.web.exposure.include=health, prometheus
    management.endpoint.prometheus.enabled=true
    logging.level.root=INFO
    logging.level.com.rupeesense.fi=DEBUG
    logging.level.org.zalando.logbook=TRACE
    
    # Exclude actuator endpoints from being logged
    logbook.exclude=/actuator/**
    logbook.format.style=http
    logbook.filter.enabled=true
    logbook.secure-filter.enabled=true
    
    # Obfuscate specific headers and parameters
    logbook.obfuscate.headers=Authorization
    logbook.obfuscate.parameters=access_token,refresh_token
