apiVersion: v1
kind: ConfigMap
metadata:
  name: fiu-service-app-config
data:
  spring.datasource.url: jdbc:postgresql://10.52.0.3:5432/fiu_datastore?useSSL=false
  spring.datasource.username: postgres
  spring.datasource.password: "*********" # This is a secret
  spring.jpa.hibernate.ddl-auto: update
  app.fiu.fiu-id: setu-fiu-id
