apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiu-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiu-application
  template:
    metadata:
      labels:
        app: fiu-application
    spec:
      serviceAccountName: fiu-application-service-account
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: fiu-service
          image: ghcr.io/rupeesense/fiu-application:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          args:
            - "java"
            - "-jar"
            - "fiu-application.jar"
            - "com.rupeesense.fi.FIUServiceApplication"
            - "--spring.config.location=/config/application.properties, /secrets/app-secrets.properties"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: app-secret-mount
              mountPath: /secrets
      imagePullSecrets:
        - name: ghcr-creds
      volumes:
        - name: config-volume
          configMap:
            name: fiu-application-config
        - name: app-secret-mount
          secret:
            secretName: fiu-application-secret
