apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiu-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiu-application
  template:
    metadata:
      labels:
        app: fiu-application
    spec:
      containers:
        - name: fiu-service
          image: ghcr.io/rupeesense/fiu-application:main
          ports:
            - containerPort: 8080
          args:
            - "java"
            - "-jar"
            - "fiu-application.jar"
            - "com.rupeesense.fi.FIUServiceApplication"
            - "--spring.config.location=/config/application.properties"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      imagePullSecrets:
        - name: ghcr-creds
      volumes:
        - name: config-volume
          configMap:
            name: fiu-application-config
