apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: account-aggregator
resources:
  - deployment.yaml
  - service.yaml
  - configMap.yaml

commonLabels:
    app: fiu-application

