apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rs-aa-dev
resources:
  - deployment.yaml
  - service.yaml
  - configMap.yaml
  - secret.yaml
  - serviceAccount.yaml

commonLabels:
    app: fiu-application
