apiVersion: v1
kind: Service
metadata:
  name: fiu-application-service
  labels:
    app: fiu-application
spec:
  type: NodePort
  selector:
    app: fiu-application
  ports:
    - port: 8080
      targetPort: 8080
